export const PROCESANDO = 'PROCESANDO';
export const ERROR = 'ERROR';

export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';

export const CONSULTAR_PRODUCTOS_EXITO = 'CONSULTAR_PRODUCTOS_EXITO'

export const ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO'

export const SELECCIONAR_PRODUCTO_EDITAR = 'SELECCIONAR_PRODUCTO_EDITAR'
export const EDITAR_PRODUCTO_EXITO = 'EDITAR_PRODUCTO_EXITO'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
